### ISSUE TITLE
TODO for this project

### ISSUE THREAD

**Issue by AryToNeX** [AryToNeX/RGBDuino#2]
Most of the things are already implemented, however:

- [ ] Status MUST be cached, this allows the daemon to start and load the previous status. Useful for wallpaper color caching, chosen color caching.
- [ ] CLI tool MUST have a "full remote" mode where it can connect and communicate to daemons in LAN.
- [ ] Daemon MUST accept wallpaper colors and cover art colors from the LAN as well as display them. Write some code to allow this.

**Comment by AryToNeX** [comment]
Milestone 1 of the Remote Update literally fired this TO-DO list. Now let's face the bugs
